package model;
// Generated Jun 7, 2022 11:30:50 PM by Hibernate Tools 4.3.1



/**
 * TblOrderdetail generated by hbm2java
 */
public class TblOrderdetail  implements java.io.Serializable {


     private Integer idProduct;
     private TblOrder tblOrder;
     private TblProduct tblProduct;
     private String productName;
     private int quantity;
     private long price;
     private long total;

    public TblOrderdetail() {
    }

    public TblOrderdetail(TblOrder tblOrder, TblProduct tblProduct, String productName, int quantity, long price, long total) {
       this.tblOrder = tblOrder;
       this.tblProduct = tblProduct;
       this.productName = productName;
       this.quantity = quantity;
       this.price = price;
       this.total = total;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public TblOrder getTblOrder() {
        return this.tblOrder;
    }
    
    public void setTblOrder(TblOrder tblOrder) {
        this.tblOrder = tblOrder;
    }
    public TblProduct getTblProduct() {
        return this.tblProduct;
    }
    
    public void setTblProduct(TblProduct tblProduct) {
        this.tblProduct = tblProduct;
    }
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }




}


