package model;
// Generated Jun 7, 2022 11:30:50 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblOrder generated by hbm2java
 */
public class TblOrder  implements java.io.Serializable {


     private Integer orderId;
     private TblUser tblUser;
     private Date orderDate;
     private int status;
     private byte delivered;
     private Date deliveryDate;
     private Integer discount;
     private long total;
     private Set<TblOrderdetail> tblOrderdetails = new HashSet<TblOrderdetail>(0);

    public TblOrder() {
    }

	
    public TblOrder(TblUser tblUser, Date orderDate, int status, byte delivered, long total) {
        this.tblUser = tblUser;
        this.orderDate = orderDate;
        this.status = status;
        this.delivered = delivered;
        this.total = total;
    }
    public TblOrder(TblUser tblUser, Date orderDate, int status, byte delivered, Date deliveryDate, Integer discount, long total, Set<TblOrderdetail> tblOrderdetails) {
       this.tblUser = tblUser;
       this.orderDate = orderDate;
       this.status = status;
       this.delivered = delivered;
       this.deliveryDate = deliveryDate;
       this.discount = discount;
       this.total = total;
       this.tblOrderdetails = tblOrderdetails;
    }
   
    public Integer getOrderId() {
        return this.orderId;
    }
    
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }
    public TblUser getTblUser() {
        return this.tblUser;
    }
    
    public void setTblUser(TblUser tblUser) {
        this.tblUser = tblUser;
    }
    public Date getOrderDate() {
        return this.orderDate;
    }
    
    public void setOrderDate(Date orderDate) {
        this.orderDate = orderDate;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }
    public byte getDelivered() {
        return this.delivered;
    }
    
    public void setDelivered(byte delivered) {
        this.delivered = delivered;
    }
    public Date getDeliveryDate() {
        return this.deliveryDate;
    }
    
    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }
    public Integer getDiscount() {
        return this.discount;
    }
    
    public void setDiscount(Integer discount) {
        this.discount = discount;
    }
    public long getTotal() {
        return this.total;
    }
    
    public void setTotal(long total) {
        this.total = total;
    }
    public Set<TblOrderdetail> getTblOrderdetails() {
        return this.tblOrderdetails;
    }
    
    public void setTblOrderdetails(Set<TblOrderdetail> tblOrderdetails) {
        this.tblOrderdetails = tblOrderdetails;
    }




}


