package model;
// Generated May 31, 2022 1:13:33 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TblProductcategory generated by hbm2java
 */
public class TblProductcategory  implements java.io.Serializable {


     private Integer categoryId;
     private TblProductcategory tblProductcategory;
     private String name;
     private int seoTilte;
     private byte status;
     private int sort;
     private String metaKeywords;
     private String metaDescriptions;
     private Integer createBy;
     private Date createDate;
     private Integer updateBy;
     private Date updateDate;
     private Set<TblProduct> tblProducts = new HashSet<TblProduct>(0);
     private Set<TblProductcategory> tblProductcategories = new HashSet<TblProductcategory>(0);

    public TblProductcategory() {
    }

	
    public TblProductcategory(String name, int seoTilte, byte status, int sort, Date createDate) {
        this.name = name;
        this.seoTilte = seoTilte;
        this.status = status;
        this.sort = sort;
        this.createDate = createDate;
    }
    public TblProductcategory(TblProductcategory tblProductcategory, String name, int seoTilte, byte status, int sort, String metaKeywords, String metaDescriptions, Integer createBy, Date createDate, Integer updateBy, Date updateDate, Set<TblProduct> tblProducts, Set<TblProductcategory> tblProductcategories) {
       this.tblProductcategory = tblProductcategory;
       this.name = name;
       this.seoTilte = seoTilte;
       this.status = status;
       this.sort = sort;
       this.metaKeywords = metaKeywords;
       this.metaDescriptions = metaDescriptions;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.tblProducts = tblProducts;
       this.tblProductcategories = tblProductcategories;
    }
   
    public Integer getCategoryId() {
        return this.categoryId;
    }
    
    public void setCategoryId(Integer categoryId) {
        this.categoryId = categoryId;
    }
    public TblProductcategory getTblProductcategory() {
        return this.tblProductcategory;
    }
    
    public void setTblProductcategory(TblProductcategory tblProductcategory) {
        this.tblProductcategory = tblProductcategory;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public int getSeoTilte() {
        return this.seoTilte;
    }
    
    public void setSeoTilte(int seoTilte) {
        this.seoTilte = seoTilte;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public int getSort() {
        return this.sort;
    }
    
    public void setSort(int sort) {
        this.sort = sort;
    }
    public String getMetaKeywords() {
        return this.metaKeywords;
    }
    
    public void setMetaKeywords(String metaKeywords) {
        this.metaKeywords = metaKeywords;
    }
    public String getMetaDescriptions() {
        return this.metaDescriptions;
    }
    
    public void setMetaDescriptions(String metaDescriptions) {
        this.metaDescriptions = metaDescriptions;
    }
    public Integer getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
    public Set<TblProduct> getTblProducts() {
        return this.tblProducts;
    }
    
    public void setTblProducts(Set<TblProduct> tblProducts) {
        this.tblProducts = tblProducts;
    }
    public Set<TblProductcategory> getTblProductcategories() {
        return this.tblProductcategories;
    }
    
    public void setTblProductcategories(Set<TblProductcategory> tblProductcategories) {
        this.tblProductcategories = tblProductcategories;
    }




}


