package model;
// Generated May 31, 2022 1:13:33 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TblProduct generated by hbm2java
 */
public class TblProduct  implements java.io.Serializable {


     private Integer productId;
     private TblBrand tblBrand;
     private TblProductcategory tblProductcategory;
     private TblSupplier tblSupplier;
     private String name;
     private String seoTilte;
     private String image;
     private String listImages;
     private long price;
     private int quantity;
     private int vat;
     private byte status;
     private int warranty;
     private Date hot;
     private String descriptions;
     private String detail;
     private int views;
     private Integer metaKeywords;
     private Integer metaDescriptions;
     private Integer createBy;
     private Date createDate;
     private Integer updateBy;
     private Integer updateDate;
     private TblOrderdetail tblOrderdetail;

    public TblProduct() {
    }

	
    public TblProduct(String name, String seoTilte, long price, int quantity, int vat, byte status, int warranty, int views, Date createDate) {
        this.name = name;
        this.seoTilte = seoTilte;
        this.price = price;
        this.quantity = quantity;
        this.vat = vat;
        this.status = status;
        this.warranty = warranty;
        this.views = views;
        this.createDate = createDate;
    }
    public TblProduct(TblBrand tblBrand, TblProductcategory tblProductcategory, TblSupplier tblSupplier, String name, String seoTilte, String image, String listImages, long price, int quantity, int vat, byte status, int warranty, Date hot, String descriptions, String detail, int views, Integer metaKeywords, Integer metaDescriptions, Integer createBy, Date createDate, Integer updateBy, Integer updateDate, TblOrderdetail tblOrderdetail) {
       this.tblBrand = tblBrand;
       this.tblProductcategory = tblProductcategory;
       this.tblSupplier = tblSupplier;
       this.name = name;
       this.seoTilte = seoTilte;
       this.image = image;
       this.listImages = listImages;
       this.price = price;
       this.quantity = quantity;
       this.vat = vat;
       this.status = status;
       this.warranty = warranty;
       this.hot = hot;
       this.descriptions = descriptions;
       this.detail = detail;
       this.views = views;
       this.metaKeywords = metaKeywords;
       this.metaDescriptions = metaDescriptions;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.tblOrderdetail = tblOrderdetail;
    }
   
    public Integer getProductId() {
        return this.productId;
    }
    
    public void setProductId(Integer productId) {
        this.productId = productId;
    }
    public TblBrand getTblBrand() {
        return this.tblBrand;
    }
    
    public void setTblBrand(TblBrand tblBrand) {
        this.tblBrand = tblBrand;
    }
    public TblProductcategory getTblProductcategory() {
        return this.tblProductcategory;
    }
    
    public void setTblProductcategory(TblProductcategory tblProductcategory) {
        this.tblProductcategory = tblProductcategory;
    }
    public TblSupplier getTblSupplier() {
        return this.tblSupplier;
    }
    
    public void setTblSupplier(TblSupplier tblSupplier) {
        this.tblSupplier = tblSupplier;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSeoTilte() {
        return this.seoTilte;
    }
    
    public void setSeoTilte(String seoTilte) {
        this.seoTilte = seoTilte;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public String getListImages() {
        return this.listImages;
    }
    
    public void setListImages(String listImages) {
        this.listImages = listImages;
    }
    public long getPrice() {
        return this.price;
    }
    
    public void setPrice(long price) {
        this.price = price;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public int getVat() {
        return this.vat;
    }
    
    public void setVat(int vat) {
        this.vat = vat;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }
    public int getWarranty() {
        return this.warranty;
    }
    
    public void setWarranty(int warranty) {
        this.warranty = warranty;
    }
    public Date getHot() {
        return this.hot;
    }
    
    public void setHot(Date hot) {
        this.hot = hot;
    }
    public String getDescriptions() {
        return this.descriptions;
    }
    
    public void setDescriptions(String descriptions) {
        this.descriptions = descriptions;
    }
    public String getDetail() {
        return this.detail;
    }
    
    public void setDetail(String detail) {
        this.detail = detail;
    }
    public int getViews() {
        return this.views;
    }
    
    public void setViews(int views) {
        this.views = views;
    }
    public Integer getMetaKeywords() {
        return this.metaKeywords;
    }
    
    public void setMetaKeywords(Integer metaKeywords) {
        this.metaKeywords = metaKeywords;
    }
    public Integer getMetaDescriptions() {
        return this.metaDescriptions;
    }
    
    public void setMetaDescriptions(Integer metaDescriptions) {
        this.metaDescriptions = metaDescriptions;
    }
    public Integer getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(Integer createBy) {
        this.createBy = createBy;
    }
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
    public Integer getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(Integer updateBy) {
        this.updateBy = updateBy;
    }
    public Integer getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Integer updateDate) {
        this.updateDate = updateDate;
    }
    public TblOrderdetail getTblOrderdetail() {
        return this.tblOrderdetail;
    }
    
    public void setTblOrderdetail(TblOrderdetail tblOrderdetail) {
        this.tblOrderdetail = tblOrderdetail;
    }




}


