package model;
// Generated May 31, 2022 8:33:18 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * TblSupplier generated by hbm2java
 */
public class TblSupplier  implements java.io.Serializable {


     private Integer supplierId;
     private String name;
     private String email;
     private String phones;
     private String address;
     private Set<TblProduct> tblProducts = new HashSet<TblProduct>(0);

    public TblSupplier() {
    }

	
    public TblSupplier(String name, String phones) {
        this.name = name;
        this.phones = phones;
    }
    public TblSupplier(String name, String email, String phones, String address, Set<TblProduct> tblProducts) {
       this.name = name;
       this.email = email;
       this.phones = phones;
       this.address = address;
       this.tblProducts = tblProducts;
    }
   
    public Integer getSupplierId() {
        return this.supplierId;
    }
    
    public void setSupplierId(Integer supplierId) {
        this.supplierId = supplierId;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhones() {
        return this.phones;
    }
    
    public void setPhones(String phones) {
        this.phones = phones;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Set<TblProduct> getTblProducts() {
        return this.tblProducts;
    }
    
    public void setTblProducts(Set<TblProduct> tblProducts) {
        this.tblProducts = tblProducts;
    }




}


